routes/web.php
<?php

use App\Http\Controllers\dashboard;
use App\Http\Controllers\ProductsTableController;
use App\Http\Controllers\store;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', [store::class, 'index'])->name('store');
Route::post('/addtocart', [store::class, 'addtocart'])->name('addcart');
Route::get('/cart', [store::class, 'cart'])->name('cart');
Route::post('/updatecart', [store::class, 'updatecart'])->name('updatecart');
Route::post('/deleteitem', [store::class, 'deleteitem'])->name('deleteitem');
Route::post('/subscribe', [store::class, 'subscribe'])->name('subscribe');
Route::post('/success', [store::class, 'success'])->name('success');

Route::get('/mailable', function () {
    $cart = session('cart');

    return new App\Mail\Paymentcomplete($cart);
});


Route::get('/dashboard', [dashboard::class, 'index'])->middleware(['auth'])->name('dashboard');
Route::get('/products', [ProductsTableController::class, 'index'])->middleware(['auth'])->name('products');
Route::get('/products/add', [ProductsTableController::class, 'create'])->middleware(['auth'])->name('products.add');
Route::post('/products/store', [ProductsTableController::class, 'store'])->middleware(['auth'])->name('products.store');
Route::get('/products/edit/{id}', [ProductsTableController::class, 'edit'])->middleware(['auth'])->name('products.edit');
Route::post('/products/update', [ProductsTableController::class, 'update'])->middleware(['auth'])->name('products.update');
Route::post('/products/delete', [ProductsTableController::class, 'destroy'])->middleware(['auth'])->name('products.delete');

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/addProducts.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add new product') }}
        </h2>
    </x-slot>
    <div>
        <form method="POST" action="{{route('products.store')}}" enctype="multipart/form-data">
            @csrf
            <x-label for="name" :value="__('Name')" />
            <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" autofocus />
            @error('name')
            <p class="text-xs text-red-500">{{$message}}</p>
            @enderror

            <x-label for="description" :value="__('Description')" />
            <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="old('description')" autofocus />
            @error('description')
            <p class="text-xs text-red-500">{{$message}}</p>
            @enderror

            <x-label for="price" :value="__('Price')" />
            <x-input id="price" class="block mt-1 w-full" type="text" name="price" :value="old('price')" autofocus />
            @error('price')
            <p class="text-xs text-red-500">{{$message}}</p>
            @enderror

            <x-label for="image">Add image</x-label>
            <input name="image" id="image" type="file">

            <button type="submit">Submit</button>
        </form>
    </div>
</x-app-layout>

resources/views/cart.blade.php
<x-guest-layout>
    <div class="flex">
        <div>
        @if (empty($cart))

            <p>the cart is empty</p>
        @else
            @foreach ($cart as $product)
                <div class="mx-4 my-4 p-4 rounded-lg bg-gray-50 text-black shadow-lg hover:shadow-inner grid grid-cols-2">
                    <div>
                        <p>{{$product['name']}}</p>
                        <img class="h-24" src="{{$product['image']}}" alt="">
                    </div>

                        <div class="  ">
                            <p>{{$product['description']}}</p>

                            <p>{{$product['price']*$product['quantity']}} €</p>
                            <form action="{{route('updatecart')}}" method="post">
                                @csrf
                                <input type="hidden" value="{{$product['id']}}" name="id">
                                <input type="number" value="{{$product['quantity']}}" name="quantity">
                                <button type="submit" >Update cart</button>
                            </form>
                            <form action="{{route('deleteitem')}}" method="post">
                                @csrf
                                <input type="hidden" value="{{$product['id']}}" name="id">
                                <button type="submit">delete</button>
                            </form>
                        </div>

                </div>
            @endforeach
        @endif
    </div>
    <div>
        <div class="w-96 h-36 flex-col border-2">
            <input id="card-holder-name" type="text" placeholder="Cardholder name">

        <!-- Stripe Elements Placeholder -->
        <div class="p-2" id="card-element"></div>

        <button class=" bg-blue-400 h-12 px-4 text-white text-xl rounded " id="card-button">
            Process Payment
        </button>
        </div>
    </div>
</div>
    <script src="https://js.stripe.com/v3/"></script>

    <script>


        const stripe = Stripe('pk_test_51KH68LElkTHhFkptzMSgq6q1AEKI1ZK1JpS1QtQweiQyyznB108uuMCl3MQgZ5xyrUaHeK3RlrZSMG9IWaRM53IP00urne4ZFt');

        const elements = stripe.elements();
        const cardElement = elements.create('card');

        cardElement.mount('#card-element');

        const cardHolderName = document.getElementById('card-holder-name');
const cardButton = document.getElementById('card-button');

cardButton.addEventListener('click', async (e) => {
    const { paymentMethod, error } = await stripe.createPaymentMethod(
        'card', cardElement, {
            billing_details: { name: cardHolderName.value }
        }
    );

    if (error) {
        // Display "error.message" to the user...
    } else {
        axios.post('/subscribe',{
                        payment_method: paymentMethod.id,
                    }).then((data)=>{
                        handleSubmit(data.data.paymentIntent)
                      //  stripe.confirmCardPayment(data.data.paymentIntent.client_secret,
                     //  {
                      //      payment_method: {
                      //          card: cardElement
                         //   }
                     //   })
                    });


    }

});

async function handleSubmit(paymentIntent) {
 await stripe.confirmCardPayment(
    paymentIntent.client_secret,
    {
        payment_method: {
            card:cardElement
            }
    }
  ).then(res  => {
      if(res.paymentIntent.status === 'succeeded')
      axios.post('/success')
      .then(window.location.replace('/'));
  })

//   if (error.type === "card_error" || error.type === "validation_error") {
//     showMessage(error.message);
//   } else {
//     showMessage("An unexpected error occured.");
//   }
}
    </script>
</x-guest-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @foreach ($users as $user)
                        <p>{{$user}}</p>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/products.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Products') }}
        </h2>
    </x-slot>
    <div>
        <a class='rounded px-2 py-1 bg-gray-800 text-white' href="{{route('products.add')}}">Add new product</a>
        @foreach ($products as $product)
        <div class="flex flex-col">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                  <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                      <tr>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Name
                        </th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Description
                        </th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Price
                        </th>
                        <th scope="col" class="relative px-6 py-3">
                          <span class="sr-only">Edit</span>
                        </th>
                      </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                      <tr>
                        <div class="flex-shrink-0 h-10 w-10">
                        <td class="px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                                <img class="w-80" src="{{$product->image}}" alt="product image" >
                            <div class="ml-4">
                                <div class="text-sm font-medium text-gray-900">
                                    {{$product->name}}
                                </div>
                            </div>
                        </div>
                        </div>
                          <div class="flex items-center">
                            <div class="ml-4">
                            </div>
                          </div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <p>{{$product->description}}</p>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                          <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                            <p>{{$product->price}} €</p>
                          </span>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <a href="{{route('products.edit', $product->id)}}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
                        </td>
                        <td>
                            <form action="{{route('products.delete')}}" method="POST">
                                @csrf
                                <input type="hidden" name="id" value="{{$product->id}}">
                                <button class="text-red-400" type="submit">Delete</button>
                            </form>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
    </div>
    @endforeach
</x-app-layout>